# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      - name: SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_SSH_HOST }} # 서버  ip주소
          username: ${{ secrets.SERVER_SSH_USERNAME }} # 서버 유저이름
          key: ${{ secrets.SERVER_SSH_KEY }} # AWS 연결 키
          port: ${{ secrets.SERVER_SSH_PORT }} # 서버 연결 포트
          script: |
            sh update.sh
